- name: Install Nginx
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy index page
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644

    - name: Start Nginx
      service:
        name: nginx
        state: started
