- name: Install and configure Nginx reverse proxy for ECS app
  hosts: all
  become: true
  vars:
    backend_host: "{{ lookup('env', 'NLB_DNS') | default('ecs-nlb-949f15e0e2367034.elb.ap-southeast-1.amazonaws.com') }}"
    backend_port: 8080

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Copy index page
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644

    - name: Upload custom nginx.conf
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        mode: 0644
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
