name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - pre-prod

jobs:
  terraform:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        run: |
          cd terraform/envs/${{ github.event.inputs.environment }}
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/envs/${{ github.event.inputs.environment }}
          terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply (dev/uat)
        if: ${{ github.event.inputs.environment != 'pre-prod' }}
        run: |
          cd terraform/envs/${{ github.event.inputs.environment }}
          terraform apply -var-file="terraform.tfvars" -auto-approve

      - name: Manual Approval Required (pre-prod)
        if: ${{ github.event.inputs.environment == 'pre-prod' }}
        run: |
          echo "Manual approval required before applying to PRE-PROD."
          echo "Skipping auto-apply. Please review and apply manually if needed."