name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version tag (e.g., 0.0.0)'
        required: true
        default: '0.0.0'

env:
  AWS_REGION: "ap-southeast-1"
  ECR_REPOSITORY: "143735903781.dkr.ecr.ap-southeast-1.amazonaws.com/aj3-aws-infra-ecr-repo-dev"
  IMAGE_TAG: ${{ github.event.inputs.version }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -f repos/vprofile-project/Docker-app/Dockerfile -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag image as latest (optional)
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:latest

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REPOSITORY:latest
